-- Create USERS table for Spring Security authentication
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    USER_TYPE VARCHAR2(20) NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    CONSTRAINT CHK_USER_TYPE CHECK (USER_TYPE IN ('ADMIN', 'MANAGER', 'USER')),
    CONSTRAINT CHK_ENABLED CHECK (ENABLED IN (0, 1))
);

-- Insert sample users with properly generated BCrypt encoded passwords
-- Username: admin, Password: admin123
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'ADMIN', 1, 'System', 'Administrator', 'admin@bank.com');

-- Username: manager, Password: manager123
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('manager', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3Vq/EVBn/lyBVtQdxruim/G', 'MANAGER', 1, 'Bank', 'Manager', 'manager@bank.com');

-- Username: user, Password: user123
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('user', '$2a$10$DowJones.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'USER', 1, 'Regular', 'User', 'user@bank.com');

-- Simple test users with password "test123"
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('testadmin', '$2a$10$eImiTXuWVxfM37uY4JANjOsz.Zr7VaBL6JdR6w/Y6.Up4hr3qAdqu', 'ADMIN', 1, 'Test', 'Admin', 'testadmin@bank.com');

INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('testuser', '$2a$10$eImiTXuWVxfM37uY4JANjOsz.Zr7VaBL6JdR6w/Y6.Up4hr3qAdqu', 'USER', 1, 'Test', 'User', 'testuser@bank.com');

COMMIT;

-- Verify the data
SELECT USER_ID, USERNAME, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL FROM USERS;
