-- Create USERS table for Spring Security authentication
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL, -- BCrypt encoded passwords
    USER_TYPE VARCHAR2(20) NOT NULL, -- ADMIN, MANAGER, USER
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL, -- 1 for enabled, 0 for disabled
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    CONSTRAINT CHK_USER_TYPE CHECK (USER_TYPE IN ('ADMIN', 'MANAGER', 'USER')),
    CONSTRAINT CHK_ENABLED CHECK (ENABLED IN (0, 1))
);

-- Insert sample users with BCrypt encoded passwords
-- Password: admin123 (BCrypt encoded)
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'ADMIN', 1, 'System', 'Administrator', 'admin@bank.com');

-- Password: manager123 (BCrypt encoded)
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('manager', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3Vq/EVBn/lyBVtQdxruim/Ge6', 'MANAGER', 1, 'Bank', 'Manager', 'manager@bank.com');

-- Password: user123 (BCrypt encoded)
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('user', '$2a$10$DowJonesUFFHFFHFFHFFHuODvanG198WvYGG2Uo6S/7eWndy3Apo6', 'USER', 1, 'Regular', 'User', 'user@bank.com');

-- Password: teller123 (BCrypt encoded)
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('teller', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'USER', 1, 'Bank', 'Teller', 'teller@bank.com');

-- Password: customer123 (BCrypt encoded)
INSERT INTO USERS (USERNAME, PASSWORD, USER_TYPE, ENABLED, FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('customer', '$2a$10$HhwzxQZHuSqZ9RjXQe1L3uK5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z', 'USER', 1, 'John', 'Customer', 'customer@email.com');

COMMIT;

-- Verify the data
SELECT * FROM USERS;
